# Gitpod YAML configuration for a Terraform workshop
image: gitpod/workspace-full

tasks:
  - name: Build
    init: |
      apt -y update && apt -y install gnupg software-properties-common
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      apt -y update && apt -y install terraform
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      ./aws/install
  - name: Setup
    init: |
      gp idp login aws --role-arn arn:aws:iam::778072100102:role/gitpod-demos-power-user
      aws sts get-caller-identity
      echo "Welcome to your workstation! Terraform is installed and ready to build on AWS."
